### ISSUE TITLE
Update PyPI release

### ISSUE THREAD

**Issue by sneakers-the-rat** [datajoint/element-array-ephys#67]
Hello! Looks like the pre-release version is about a year old, and the version in the repo is still 0.1.0b0 despite substantial changes since then. Wondering if there's a particular reason the PyPI version isn't being kept synchronized, or if I should just pin a commit in the git repository rather than by package version in downstream packages?

related to
https://github.com/datajoint/element-session/issues/18

**Comment by kabilar** [comment]
Thanks for the report @sneakers-the-rat.

We just went through a development sprint.  We will be updating the version, tagging, and releasing these changes to pypi by the end of May.  For the interim, please install from source:

```
pip install git+https://github.com/datajoint/element-array-ephys.git
```

Install a specific commit:
```
pip install git+https://github.com/datajoint/element-array-ephys.git@<Enter commit hash>
```

**Comment by kabilar** [comment]
Hi @sneakers-the-rat, you can now find the latest release (`0.1.1`) on [PyPI](https://pypi.org/project/element-array-ephys/0.1.1/).  Thanks.
